name: ruff

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:

jobs:
  ruff:
    # runs-on: k8s-eng-gpu-32G-a5000-24G
    runs-on: aws-avx2-32G-a10g-24G
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.1.5
    - name: Analysing the code with ruff
      run: |
        ruff vllm tests
    - name: run this
      run: |
        echo "boo hoo"
